services:
  vizela-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    container_name: vizela-viagens-web
    restart: always
    environment:
      - NODE_ENV=production
      - BACKEND_URL_INTERNAL=${BACKEND_URL_INTERNAL}
    networks:
      exposed:
        ipv4_address: 172.30.0.190

networks:
  exposed:
    external: true
    name: blackmesa
