import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import _NavBar from "@/app/pages/_navbar.tsx";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <_NavBar />
        <div className="pt-20">{children}</div>
      </body>
    </html>
  );
}
